---
name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: elasticsearch:7.7.1
        ports:
          - 9200:9200
          - 9300:9300
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s  --health-timeout=5s --health-retries=10

    steps:

      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - run: gem install bundler -v 2.1

      - run: bundle install

      - run: bundle exec rake default
